version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  event-producer:
    build: ./producer
    container_name: event-producer
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      TOPIC_NAME: example-topic
      INTERVAL_MS: 1000

  # Pinot components
  pinot-controller:
    image: apachepinot/pinot:0.12.1
    container_name: pinot-controller
    command: "StartController -zkAddress zookeeper:2181 -clusterName pinot-kafka-demo"
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      JAVA_OPTS: "-Xms512m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"

  pinot-broker:
    image: apachepinot/pinot:0.12.1
    container_name: pinot-broker
    command: "StartBroker -zkAddress zookeeper:2181 -clusterName pinot-kafka-demo"
    restart: unless-stopped
    ports:
      - "8099:8099"
    depends_on:
      pinot-controller:
        condition: service_started
    environment:
      JAVA_OPTS: "-Xms512m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"

  pinot-server:
    image: apachepinot/pinot:0.12.1
    container_name: pinot-server
    command: "StartServer -zkAddress zookeeper:2181 -clusterName pinot-kafka-demo"
    restart: unless-stopped
    depends_on:
      pinot-broker:
        condition: service_started
    environment:
      JAVA_OPTS: "-Xms512m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
